#ToDo encrypt subscriptionKey with JASYPT
azure_translator_client:
  url: "https://api.cognitive.microsofttranslator.com/translate?api-version=3.0&to=en"
  subscriptionKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  region: "westeurope"